### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by ghost** [Robomikel/Steam-Server-Manager#102]
Hi, how do I run it? I wrote "npm install" and then "npm start" and it doesn't work. Can someone help me?

**Comment by Robomikel** [comment]
I have a Wiki, have you checked these out. its a script essentially, download, unzip. run from download location. see params in commands section of wiki. 

https://github.com/Robomikel/Steam-Server-Manager/wiki/Installing-SSM

https://github.com/Robomikel/Steam-Server-Manager/wiki/Install-your-first-Dedicated-Server-with-SSM

https://github.com/Robomikel/Steam-Server-Manager/wiki/Basic-Operations
