### ISSUE TITLE
wrong exe folder

### ISSUE THREAD

**Issue by rira2005** [Robomikel/Steam-Server-Manager#130]
Hi 

After installing a server (fe. wreckfest) the script start ist with heading "server/wreckfest" folder....
ist wrong. 

My error? or a script error?

tia

**Comment by Robomikel** [comment]
Tia, 
Change "server/wreckfest" to "Wreckfest". That variable should be the name of executable without the extension. It must have been a typo.  I updated the [default-config](https://github.com/Robomikel/config-default) as well. 

`    #                       Server Executable `    
 `   $global:executable      = "Wreckfest"`    

Thanks,

Michael

**Comment by Robomikel** [comment]
Wreckfest dev's could have moved the exe to root as well. either way let me know how it goes.

**Comment by Robomikel** [comment]
Tia, 

Did you get it working? I tested it when you posted this. After the executable variable fix it worked for me.

**Comment by Robomikel** [comment]
Did a few more updates since the wreckfest devs changed a few things and doing a final push request for this issue.
