### ISSUE TITLE
Gamedig node version update to >=16.20.0

### ISSUE THREAD

**Issue by Romboter** [Robomikel/Steam-Server-Manager#165]
See https://gamedig.github.io/library/
Says it wants Node >=16.20.0 now

**Comment by Robomikel** [comment]
I was hoping it would be a simple change. ssm.ps1 has the version number variable for nodejs. Although, it seems 16.20.0 and 16.20.2 seems to nuke the npm folder after the gamedig install. maybe its just my test host. I will have to mess with it and see if I can figure out whats going on. seems readding the folder after it nukes it seems fine.

**Comment by Robomikel** [comment]
Looks like the portable zip is not working for any versions higher than v14. Does work with prebuilt installer 20.17.0 LTS. This will have to be the workaround for now. 
https://nodejs.org/dist/v20.17.0/node-v20.17.0-x64.msi

**Comment by Robomikel** [comment]
I just release an update for nodejs fix
