### ISSUE TITLE
Rust Server Closes after load

### ISSUE THREAD

**Issue by dasKreuzer** [Robomikel/Steam-Server-Manager#166]
As description states, it unexpectedly crashes is there a solution for this?

**Comment by Robomikel** [comment]
I wasn't able to duplicate the issue. Setup fresh Windows Server 2022, VCredist, Fresh Rust install no plugins.  PSversion 5.1.20348

**Comment by Robomikel** [comment]
I tested with plugins and plugins update function. I wasn't able to duplicate it. 16GB ram, 4 vCPU, windows server
