### ISSUE TITLE
Recommend Games!

### ISSUE THREAD

**Issue by Robomikel** [Robomikel/Steam-Server-Manager#25]
Please comment and recommend games you would like to see. Preferably Steam games but I can always look into it. Need about 27 more games to hit the 100 mark.  

Any feedback is appreciated :)

**Comment by umgekehrt** [comment]
Please add Satisfactory

**Comment by Robomikel** [comment]
> Satisfactory

I can add it. Have to wait till I get paid to purchase the game. Looks like it requires a steam login for the server binaries.

**Comment by umgekehrt** [comment]
> > Satisfactory
> 
> I can add it. Have to wait till I get paid to purchase the game. Looks like it requires a steam login for the server binaries.

I was able to install it by adding this line to serverlist.csv: satisfactory,satisfactorydedicatedserver,Satisfactory,1690800,Satisfactory_default.ps1,

What I discovered is that it's still very immature and possibly not worth implementing yet. Its initial config is built through the experimental game client at this point in time and doesn't follow typical dedicated server methods.

**Comment by Robomikel** [comment]
> > > Satisfactory
> > 
> > 
> > I can add it. Have to wait till I get paid to purchase the game. Looks like it requires a steam login for the server binaries.
> 
> I was able to install it by adding this line to serverlist.csv: satisfactory,satisfactorydedicatedserver,Satisfactory,1690800,Satisfactory_default.ps1,
> 
> What I discovered is that it's still very immature and possibly not worth implementing yet. Its initial config is built through the experimental game client at this point in time and doesn't follow typical dedicated server methods.

   That's good. You can also make up  folder name not in the .csv and it will prompt for the app id. 
[I put a bullet note here](https://github.com/Robomikel/Steam-Server-Manager/wiki/Install-your-first-Dedicated-Server-with-SSM)

   Find another game in the .csv that uses Unreal Engine 4. Grab the [default-config](https://github.com/Robomikel/config-default). then edit it to fit your install. Run the install again and it should build the launch script for you. I want to add the instructions in the Wiki one day.

**Comment by Robomikel** [comment]
> > > > Satisfactory
> > > 
> > > 
> > > I can add it. Have to wait till I get paid to purchase the game. Looks like it requires a steam login for the server binaries.
> > 
> > 
> > I was able to install it by adding this line to serverlist.csv: satisfactory,satisfactorydedicatedserver,Satisfactory,1690800,Satisfactory_default.ps1,
> > What I discovered is that it's still very immature and possibly not worth implementing yet. Its initial config is built through the experimental game client at this point in time and doesn't follow typical dedicated server methods.
> 
> That's good. You can also make up folder name not in the .csv and it will prompt for the app id. [I put a bullet note here](https://github.com/Robomikel/Steam-Server-Manager/wiki/Install-your-first-Dedicated-Server-with-SSM)
> 
> Find another game in the .csv that uses Unreal Engine 4. Grab the [default-config](https://github.com/Robomikel/config-default). then edit it to fit your install. You may have to add it to check_appid.ps1 as well. Then, run the install again and it should build the launch script for you. I want to add the instructions in the Wiki one day.
> 
> Oh, and if you want send a push request. It will help alot so I don't have to purchase all the games that require steam login. :)

this is all I found for a launch command. 
https://www.reddit.com/r/SatisfactoryGame/comments/m7yek2/satisfactory_dedicated_server_guide/

it uses local appdata. Could look at the 7 days to Die default-config on how I did the backups and restore

**Comment by StubbsPKS** [comment]
Would love to see support for Eco

**Comment by Robomikel** [comment]
> Please add Satisfactory

I added Satisfactory. It's in the Pre-release Branch. Any feed back would be helpful. Just through the response in as a new Issue.

**Comment by umgekehrt** [comment]
> > Please add Satisfactory
> 
> I added Satisfactory. Any feed back would be helpful. Just through the response in as a new Issue. I haven't tested with the client because I don't own the game still. Looks like some of the initial configuration is done on first connect. [quoted from here](https://satisfactory.fandom.com/wiki/Dedicated_servers#Starting_the_server)

Thanks, I noticed some friends playing and Update 5 was officially released. The dedicated server is still experimental, but hopefully it actually works this time. If there's any feedback regarding SSM, I'll raise a new issue. Thank you so much for the update!

**Comment by Robomikel** [comment]
moving to Discussion
