### ISSUE TITLE
[Request] Add more mods like LinuxGSM

### ISSUE THREAD

**Issue by xe1os** [Robomikel/Steam-Server-Manager#75]
Hi Robomikel,

Kudos to your work.!!

Would be great if mods like Get5, csgo-pug-setup and Steamworks are added to the script.

**Comment by Robomikel** [comment]
Thanks, I will take look and see what I can do.

**Comment by Robomikel** [comment]
Okay, I just updated the pre-release branch if you want to check it out.

**Comment by xe1os** [comment]
> Okay, I just updated the pre-release branch if you want to check it out.

@Robomikel it would be great if latest development build [is](https://ci.splewis.net/job/get5/lastSuccessfulBuild/) downloaded instead of release for Get5

**Comment by Robomikel** [comment]
okay, that should work. it should over write the old plugin.

 I put the links in the ssm.ps1 to make them easy to update on the fly.

**Comment by Robomikel** [comment]
merged with Master Branch
