### ISSUE TITLE
update-mod functionality

### ISSUE THREAD

**Issue by xe1os** [Robomikel/Steam-Server-Manager#81]
@Robomikel this will help updating mods like sourcemod, metamod, get5, pugsetup, etc

**Comment by Robomikel** [comment]
ok, it took longer than I expected. try this [branch](https://github.com/Robomikel/Steam-Server-Manager/tree/github-rest-sources-mods).  you still need to specify what version of SM and MM you want to use. as before SM will update to the newest branch/build(i.e. 6502) for that version(i.e. 1.11).

- Delete/backup your local_settings.ps1
   * SSM will create a new one with these options. 
   * ```    #                               SourceMod Version```
    ```$global:smversion               = "stable" # stable / dev```
   ``` #                               MetaMod Version```
    ```$global:mmversion               = "stable" # stable / master ```
-  Install the mods you would like `install-mods`
   * SSM will create a `mods.json` in the server folder
- you can now run `update-mods`
  * it will only update if the new download is different than the one installed 
  * create scheduled task for automation 

> it's kinda a sneak preview. I still have to do more testing but I think its close to being merged with master branch
